env:
  browser: true
  es2021: true
extends: standard-with-typescript
parserOptions:
  project: ["./tsconfig.json"]
  ecmaVersion: latest
  sourceType: module
rules: { "@typescript-eslint/explicit-function-return-type": "off" }
